//! Tray icon byte buffer.
//!
//! ksni accepts ARGB32 raw bytes plus width/height. We ship the
//! tray icon as a pre-rasterized 22x22 ARGB32 buffer (1936 bytes)
//! generated from `data/com.sdr.rs.svg` by `scripts/regen-tray-icon.sh`
//! and committed to the repo. No runtime SVG dep, no `librsvg`
//! transitive tree, no `cairo` initialisation cost.
//!
//! Trade-off: re-run `scripts/regen-tray-icon.sh` whenever the SVG
//! source changes. For an app icon that ships once and stays put,
//! that's a vastly better deal than a dependency cluster pulling
//! `nalgebra` / `paste` / `fxhash` (the last two unmaintained per
//! RUSTSEC) just to render 484 pixels at startup. Per #512.

/// Bytes are layed out row-major, network-byte-order ARGB32 — the
/// SNI wire format. ksni passes them straight through.
pub(crate) const TRAY_ICON_SIZE: i32 = 22;

/// Pre-baked 22x22 tray icon bytes. Generated by
/// `scripts/regen-tray-icon.sh` from `data/com.sdr.rs.svg`.
pub(crate) const TRAY_ICON_22X22_ARGB32: &[u8] =
    include_bytes!("../../../data/com.sdr.rs.tray22.argb32");

/// Compile-time sanity: the buffer has to be exactly the size
/// `width * height * 4` bytes for the ksni `Icon` to be valid.
const _: () = assert!(
    TRAY_ICON_22X22_ARGB32.len() == (TRAY_ICON_SIZE * TRAY_ICON_SIZE * 4) as usize,
    "tray icon byte length must equal width*height*4 — regenerate via scripts/regen-tray-icon.sh",
);

/// Returns the tray icon as `(width, height, ARGB32 bytes)`. The
/// returned `Vec<u8>` is a fresh copy each call — ksni's `Icon`
/// type wants owned bytes.
pub(crate) fn current_icon() -> (i32, i32, Vec<u8>) {
    (
        TRAY_ICON_SIZE,
        TRAY_ICON_SIZE,
        TRAY_ICON_22X22_ARGB32.to_vec(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn buffer_length_matches_size() {
        // Compile-time const_assert covers this, but a runtime test
        // makes the failure mode legible if the const ever lands
        // wrong. Cheap.
        assert_eq!(
            TRAY_ICON_22X22_ARGB32.len(),
            (TRAY_ICON_SIZE * TRAY_ICON_SIZE * 4) as usize,
        );
    }

    #[test]
    fn icon_has_at_least_one_opaque_pixel() {
        // The bytes are laid out [A, R, G, B] per pixel. If alpha is
        // zero everywhere the tray would just draw a hole — likely a
        // botched regen. Same check as the previous SVG-rasterize
        // path used post-render.
        assert!(
            TRAY_ICON_22X22_ARGB32.chunks(4).any(|p| p[0] != 0),
            "tray icon has zero alpha everywhere — regenerate via scripts/regen-tray-icon.sh",
        );
    }

    #[test]
    fn current_icon_returns_correct_dimensions() {
        let (w, h, bytes) = current_icon();
        assert_eq!(w, TRAY_ICON_SIZE);
        assert_eq!(h, TRAY_ICON_SIZE);
        let expected = usize::try_from(w)
            .and_then(|w| usize::try_from(h).map(|h| w * h * 4))
            .expect("positive dimensions fit in usize");
        assert_eq!(bytes.len(), expected);
    }
}
