[package]
name = "sdr-source-airspy"
version = "0.1.0"
description = "Airspy R2 / Mini USB source module"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sdr-types.workspace = true
sdr-pipeline.workspace = true
libairspy-rs.workspace = true
tracing.workspace = true

[lints]
workspace = true
