//! CCSDS pseudo-noise (PN) sequence de-randomizer.
//!
//! CCSDS 131.0-B-3 specifies a PN sequence generated by the
//! polynomial h(x) = x^8 + x^7 + x^5 + x^3 + 1, seeded with all
//! ones, period 255 bytes. The table itself is short enough that
//! medet ships it verbatim; we do the same and treat the medet
//! table as the canonical reference (it's been validated against
//! real Meteor downlinks for years).
//!
//! Frame bytes are `XOR`-ed with the PN stream during transmit to
//! break up long bit runs (helps the receiver's bit-clock stay
//! locked); receiver applies the same XOR to recover the original.
//! Sequence resets per CADU per spec — call [`Derandomizer::reset`]
//! at every CADU boundary.
//!
//! Reference (read-only): `original/medet/met_to_data.pas`
//! (the `prand` table at the top of the file). To independently
//! validate the table against the spec polynomial, the canonical
//! reference is `libfec`'s `Bp[]` in `viterbi27.c` — both produce
//! the same bytes (different LFSR-direction conventions can yield
//! visually-different tables that are equivalent mod sequence
//! ordering, so direct byte comparison against `libfec` is the
//! cleanest cross-check).

/// Length of the CCSDS PN sequence (one period).
pub const PN_PERIOD: usize = 255;

/// CCSDS PN table, copied verbatim from `medet/met_to_data.pas`.
/// This is the canonical reference for what's on the wire; see
/// the module-level doc for cross-validation guidance against
/// `libfec`'s reference table.
const PN_TABLE: [u8; PN_PERIOD] = [
    0xff, 0x48, 0x0e, 0xc0, 0x9a, 0x0d, 0x70, 0xbc, 0x8e, 0x2c, 0x93, 0xad, 0xa7, 0xb7, 0x46, 0xce,
    0x5a, 0x97, 0x7d, 0xcc, 0x32, 0xa2, 0xbf, 0x3e, 0x0a, 0x10, 0xf1, 0x88, 0x94, 0xcd, 0xea, 0xb1,
    0xfe, 0x90, 0x1d, 0x81, 0x34, 0x1a, 0xe1, 0x79, 0x1c, 0x59, 0x27, 0x5b, 0x4f, 0x6e, 0x8d, 0x9c,
    0xb5, 0x2e, 0xfb, 0x98, 0x65, 0x45, 0x7e, 0x7c, 0x14, 0x21, 0xe3, 0x11, 0x29, 0x9b, 0xd5, 0x63,
    0xfd, 0x20, 0x3b, 0x02, 0x68, 0x35, 0xc2, 0xf2, 0x38, 0xb2, 0x4e, 0xb6, 0x9e, 0xdd, 0x1b, 0x39,
    0x6a, 0x5d, 0xf6, 0x30, 0xca, 0x8a, 0xfc, 0xf8, 0x28, 0x43, 0xc6, 0x22, 0x53, 0x37, 0xaa, 0xc7,
    0xfa, 0x40, 0x76, 0x04, 0xd0, 0x6b, 0x85, 0xe4, 0x71, 0x64, 0x9d, 0x6d, 0x3d, 0xba, 0x36, 0x72,
    0xd5, 0xbb, 0xec, 0x61, 0x95, 0x15, 0xf9, 0xf0, 0x50, 0x87, 0x8c, 0x44, 0xa6, 0x6f, 0x55, 0x8f,
    0xf4, 0x80, 0xec, 0x09, 0xa0, 0xd7, 0x0b, 0xc8, 0xe2, 0xc8, 0x3a, 0xda, 0x7b, 0x74, 0x6c, 0xe4,
    0xab, 0x37, 0xd2, 0xc3, 0x2a, 0x2b, 0xf3, 0xe1, 0xa1, 0x0f, 0x18, 0x89, 0x4c, 0xde, 0xab, 0x1f,
    0xe9, 0x01, 0xd8, 0x13, 0x41, 0xae, 0x17, 0x91, 0xc5, 0x90, 0x75, 0xb4, 0xf7, 0x68, 0xd9, 0xc8,
    0x57, 0x6f, 0xa4, 0x86, 0x55, 0x57, 0xe6, 0xc3, 0x42, 0x1e, 0x31, 0x12, 0x99, 0xbd, 0x56, 0x3f,
    0xd2, 0x03, 0xb0, 0x26, 0x83, 0x5c, 0x2f, 0x23, 0x8b, 0x21, 0xea, 0x68, 0xef, 0xd1, 0xb2, 0x91,
    0xae, 0xdf, 0x49, 0x0c, 0xab, 0xae, 0xcd, 0x86, 0x84, 0x3c, 0x62, 0x25, 0x33, 0x7a, 0xad, 0x7e,
    0xa4, 0x07, 0x60, 0x4d, 0x06, 0xb8, 0x5e, 0x46, 0x16, 0x42, 0xd5, 0xd0, 0xde, 0xa2, 0x65, 0x22,
    0x5d, 0xbf, 0x92, 0x18, 0x57, 0x5d, 0x9b, 0x0c, 0x08, 0x79, 0xc4, 0x4a, 0x66, 0xf5, 0x5b,
];

/// Streaming de-randomizer. Stateful position counter; XORs each
/// input byte against the pre-computed PN table.
pub struct Derandomizer {
    pos: usize,
}

impl Default for Derandomizer {
    fn default() -> Self {
        Self::new()
    }
}

impl Derandomizer {
    #[must_use]
    pub fn new() -> Self {
        Self { pos: 0 }
    }

    /// Reset the PN-sequence position. Call at every CADU boundary
    /// — the spec restarts the sequence per CADU.
    pub fn reset(&mut self) {
        self.pos = 0;
    }

    /// Push one byte; returns the de-randomized byte.
    pub fn process(&mut self, byte: u8) -> u8 {
        let out = byte ^ PN_TABLE[self.pos];
        // Branch-wrap instead of `% PN_PERIOD`: avoids a division
        // on every byte in the hot path. The compiler is welcome
        // to recognize the `% 255` modulus and emit the same code,
        // but the branch form is unambiguously cheap.
        self.pos += 1;
        if self.pos == PN_PERIOD {
            self.pos = 0;
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pn_table_starts_with_documented_bytes() {
        // First two bytes are the canonical 0xFF, 0x48 fingerprint
        // — anyone studying CCSDS PN sequences sees these in
        // every reference implementation.
        assert_eq!(PN_TABLE[0], 0xFF, "first PN byte");
        assert_eq!(PN_TABLE[1], 0x48, "second PN byte");
    }

    #[test]
    fn pn_table_length_is_one_full_period() {
        assert_eq!(PN_TABLE.len(), PN_PERIOD);
    }

    #[test]
    fn round_trip_recovers_input() {
        // XOR is its own inverse and reset() puts us back at
        // position 0, so de-randomizing a randomized stream
        // recovers the original bytes exactly.
        let input: Vec<u8> = (0..100).collect();
        let mut d = Derandomizer::new();
        let scrambled: Vec<u8> = input.iter().map(|b| d.process(*b)).collect();
        d.reset();
        let recovered: Vec<u8> = scrambled.iter().map(|b| d.process(*b)).collect();
        assert_eq!(recovered, input);
    }

    #[test]
    fn position_wraps_at_period() {
        let mut d = Derandomizer::new();
        // Push PN_PERIOD + 5 zero bytes — XOR mask at byte
        // PN_PERIOD must equal the mask at byte 0.
        let masks: Vec<u8> = (0..PN_PERIOD + 5).map(|_| d.process(0)).collect();
        for offset in 0..5 {
            assert_eq!(
                masks[PN_PERIOD + offset],
                masks[offset],
                "PN sequence didn't wrap at byte {}",
                PN_PERIOD + offset,
            );
        }
    }
}
